apiVersion: v1
kind: Service
metadata:
  name: shop
spec:
  type: NodePort
  selector:
    app: shop                     # matches BOTH stable and canary pods
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30082
